app = 'couchtube'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8363
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[services]
concurrency = { hard_limit = 1, soft_limit = 1 }

[[vm]]
  memory = '128mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 128

[env]
  FULL_SCAN = "false"
  READONLY_MODE = "true"
  JSON_FILE_PATH = "/data/videos.json"
